#http://travis-ci.org/#!velvet/velvet
language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
#addons:
#  apt:
#    packages:
#      - libatlas-dev
#      - liblapack-dev
#      - python-numpy
#      - python-scipy
#      - python-matplotlib
install:
  #  - pip install nose
  #- python setup.py install

  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION scipy numpy matplotlib nose
  - source activate test-environment
  - python setup.py install
script:
  - nosetests -v
